# -*- coding: utf-8 -*-
"""pa2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IK9AU2_pakznyobVvIqSeOX0hMyLDvg9
"""

#2
################################################################################
import pandas as pd
import numpy as np
import seaborn as sns
###1###
df = pd.read_csv('./data/airbnb_hw.csv', low_memory=False)
print( df.shape, '\n')
df.head()
price = df['Price']
price.unique()
#for any price that has 4 digits a common is added. This turns it from an int to a string.

price = df['Price']
price = price.str.replace(',','')
print( price.unique() , '\n')
price = pd.to_numeric(price,errors='coerce')
print( price.unique() , '\n')
print( 'Total missing: ', sum( price.isnull() ) )

#there are now 0 missing value
#by replacing the ',' with numbers, we are able to turn the string values to ints


###2###

df = pd.read_csv('./data/sharks.csv', low_memory=False)
df.head()
df.columns.tolist()
df['Type'].value_counts()
type = df['Type']
type = type.replace(['Sea Disaster', 'Boat','Boating','Boatomg'],'Watercraft')
type.value_counts()
type = type.replace(['Invalid', 'Questionable','Unconfirmed','Unverified','Under investigation'],np.nan)
df['Type'] = type
del type

df['Type'].value_counts()

#first we create a temporary vector
# df['Type'].value_counts() helps looks at the different values in the col
#changing values to NA when there are uncertain to a degree, this helps clean up data


###3###
df = pd.read_csv('./data/VirginiaPretrialData2017.csv', low_memory=False)
release = df['WhetherDefendantWasReleasedPretrial']
release = release.replace(9,np.nan)
print(release.value_counts(),'\n')
sum(release.isnull())
df['WhetherDefendantWasReleasedPretrial'] = release
del release

###4###
length = df['ImposedSentenceAllChargeInContactEvent']
type = df['SentenceTypeAllChargesAtConvictionInContactEvent']
length = pd.to_numeric(length,errors='coerce')
length_NA = length.isnull()
length = length.mask( type == 4, 0)
length = length.mask( type == 9, np.nan)
length_NA = length.isnull()
print( pd.crosstab(length_NA, type), '\n')
print( np.sum(length_NA),'\n')
df['ImposedSentenceAllChargeInContactEvent'] = length
del length, type

#since changes were dismissed, cat. #4, the length is replaced by 0


#3
############################################################################
#1.
#The most recent US Census gathered information regarding race directly through a question in its questionnaire.
#This allowed respondents to self-identify.

#2.
#Racial and ethnic data serve a critical role in politics.
#First it can help ensure that districts are fairly represented in the right proportions.
#Also, it can help with funding and developing policies that address diversity.

#3.
#Some things that they do well in my opinion is that they are inclusive in their race and ethnicity questions.
#For example, they allow respondents to self identify.
#Also, it allows for online responses which increases accessibility.
#As the questionnaire transitions to an online format and more digital data collecting, it'd be beneficial for the respondents to be informed regarding data privacy and security to maintain public trust.
#In the future, there could be surveys in different languages to increase accessibility.
#To gather more useful and richer data, the Census should include a continuous feedback form so that respondents can give clarifying answers or add comments to questions.

#4.
#To gather information regarding sex and gender, it asks a straightforward, binary question: male or female.
#Things done well with the question is its simplicity, yet it is not inclusive to those who are trassgender.
#As an improvement they could include another question about gender assignment at birth versus current gender.

#5.
#First challenge that comes to mind is if the demographics will be represented accurately without introducing biases with missing data. Some good practices would be to use inclusive data collection methods, protecting privacy, and ethically using the data to avoid reinforcing stereotypes.

#6
#Inputting such sensitive attributes may lead to various privacy concerns that could infringe on peoples' privacy.
#Additionally, this might inappropriately create policy recommendations that further marginalize already underrepresented groups of people.